# Generated by Django 5.2.14 on 2026-06-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(help_text='Short form stored on the speaker (e.g. "Dr.", "Ing.").', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full name of the title (e.g. "Doctor", "Ingeniero").', max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Display order in select widgets (lower first).')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='If False, hidden from new selects but keeps existing values intact.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic title',
                'verbose_name_plural': 'Academic titles',
                'ordering': ['sort_order', 'abbreviation'],
            },
        ),
    ]
