# Generated by Django 5.2.14 on 2026-07-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_certificate_requires_quiz_event_quiz_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='faculty',
            field=models.CharField(choices=[('FACI', 'FACI - Ingeniería'), ('FACS', 'FACS - Salud'), ('FACE', 'FACE - Educación'), ('FACSECYD', 'FACSECYD - Ciencias Sociales'), ('POSGRADO', 'Posgrado / Otra'), ('COMUNIDAD', 'Comunidad Universitaria')], default='FACI', max_length=20, verbose_name='Faculty / Department'),
        ),
        migrations.AlterField(
            model_name='certificatebatch',
            name='faculty',
            field=models.CharField(choices=[('FACI', 'FACI - Ingeniería'), ('FACS', 'FACS - Salud'), ('FACE', 'FACE - Educación'), ('FACSECYD', 'FACSECYD - Ciencias Sociales'), ('POSGRADO', 'Posgrado / Otra'), ('COMUNIDAD', 'Comunidad Universitaria')], db_index=True, default='FACI', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, choices=[('FACI', 'FACI - Ingeniería'), ('FACS', 'FACS - Salud'), ('FACE', 'FACE - Educación'), ('FACSECYD', 'FACSECYD - Ciencias Sociales'), ('POSGRADO', 'Posgrado / Otra'), ('COMUNIDAD', 'Comunidad Universitaria')], db_index=True, max_length=20),
        ),
    ]
