# Generated by Django 5.2.13 on 2026-07-03 20:43

import core.base.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_program_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Feature')),
                ('content', models.TextField(blank=True, default='', verbose_name='Prompt')),
            ],
            options={
                'verbose_name': 'AI Prompt',
                'verbose_name_plural': 'AI Prompts',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('claude', 'Anthropic Claude'), ('openai', 'OpenAI (GPT)'), ('groq', 'Groq (Llama / Mixtral)')], max_length=20, unique=True, verbose_name='Proveedor')),
                ('api_key', core.base.fields.EncryptedCharField(blank=True, default='', help_text='Cifrada en reposo con Fernet.', max_length=1000)),
                ('model', models.CharField(blank=True, default='', help_text='Identificador del modelo (ej. gpt-4o-mini).', max_length=80, verbose_name='Modelo')),
                ('enabled', models.BooleanField(default=False, verbose_name='Habilitado')),
                ('priority', models.PositiveSmallIntegerField(default=100, verbose_name='Prioridad (menor = primero)')),
            ],
            options={
                'verbose_name': 'AI Provider Credential',
                'verbose_name_plural': 'AI Provider Credentials',
                'ordering': ['priority', 'provider'],
            },
        ),
    ]
