# Generated by Django 5.2.14 on 2026-07-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_evaluation_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_open',
            field=models.BooleanField(default=False, help_text='Si está apagado, el programa está en configuración y los participantes no lo ven.', verbose_name='Programa publicado'),
        ),
    ]
