# Generated by Django 5.2.13 on 2026-07-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_program_signature_inst_1_program_signature_inst_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor'), ('administrador', 'Administrador')], db_index=True, max_length=20)),
                ('module', models.CharField(db_index=True, max_length=40)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'permiso de perfil',
                'verbose_name_plural': 'permisos de perfiles',
                'ordering': ['role', 'module'],
                'unique_together': {('role', 'module')},
            },
        ),
    ]
