# Generated by Django 5.2.13 on 2026-07-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_drop_profesor_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('administrador', 'Administrador')], db_index=True, max_length=20),
        ),
    ]
