# Generated by Django 5.2.14 on 2026-06-03 01:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_faculties'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code_hash', models.CharField(help_text='SHA-256 of the 6-digit code.', max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='core.participant')),
            ],
            options={
                'verbose_name': 'Password reset token',
                'verbose_name_plural': 'Password reset tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'used_at'], name='core_passwo_token_4a5d29_idx'), models.Index(fields=['expires_at'], name='core_passwo_expires_71ae22_idx')],
            },
        ),
    ]
