# Generated by Django 5.2.14 on 2026-06-28 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_academic_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_parts',
            field=models.BooleanField(default=False, help_text='Si está activo, este evento es parte de una serie (parte 1, 2, …).', verbose_name='Seminario dividido en partes'),
        ),
        migrations.AddField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(blank=True, help_text='Para continuaciones: apunta al evento que es la primera parte.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='core.event', verbose_name='Primera parte de la serie'),
        ),
    ]
