# Generated by Django 5.2.14 on 2026-07-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_has_parts_event_parent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate_requires_quiz',
            field=models.BooleanField(default=False, help_text='Si está activo, solo se emite certificado a quien apruebe el cuestionario.', verbose_name='Requiere aprobar el quiz para el certificado'),
        ),
        migrations.AddField(
            model_name='event',
            name='quiz_enabled',
            field=models.BooleanField(default=True, help_text='Si está apagado, no se genera ni se muestra el quiz del evento.', verbose_name='Generar y mostrar cuestionario'),
        ),
        migrations.AddField(
            model_name='event',
            name='quiz_pass_threshold',
            field=models.PositiveSmallIntegerField(default=70, help_text='Porcentaje mínimo para aprobar el cuestionario (0-100).', verbose_name='Nota mínima del quiz (%)'),
        ),
    ]
