# Generated by Django 5.2.13 on 2026-07-01 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_faculty_comunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='program_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificatebatch',
            name='kind',
            field=models.CharField(choices=[('course', 'Course certificate'), ('program', 'Program certificate')], db_index=True, default='course', help_text='Course = one event; Program = groups several courses.', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='hours',
            field=models.PositiveIntegerField(default=0, help_text='Horas académicas de este curso (usadas en el certificado).', verbose_name='Horas del curso'),
        ),
        migrations.AddField(
            model_name='event',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='Habilidades que desarrolla este curso (se listan en el certificado de programa).', verbose_name='Habilidades / competencias'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Program name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('faculty', models.CharField(choices=[('FACI', 'FACI - Ingeniería'), ('FACS', 'FACS - Salud'), ('FACE', 'FACE - Educación'), ('FACSECYD', 'FACSECYD - Ciencias Sociales'), ('POSGRADO', 'Posgrado / Otra'), ('COMUNIDAD', 'Comunidad Universitaria')], db_index=True, default='FACI', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('certificate_body', models.TextField(blank=True, default='', help_text='Texto del certificado de programa. Usa {programa} y {horas} como variables. Si se deja vacío se usa un texto por defecto.', verbose_name='Program certificate body')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='core_progra_is_acti_319d36_idx'), models.Index(fields=['faculty'], name='core_progra_faculty_437535_idx')],
            },
        ),
        migrations.AddField(
            model_name='certificatebatch',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Set only for program-certificate batches.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='core.program', verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='event',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Si pertenece a un programa, se agrupa bajo él.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.program', verbose_name='Programa'),
        ),
    ]
