# Generated by Django 5.2.13 on 2026-07-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_evaluation_evaluationattempt_evaluationgrant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Imagen promocional del programa (puede generarse con IA).', null=True, upload_to='program_banners/', verbose_name='Banner image'),
        ),
    ]
