# Generated by Django 5.2.13 on 2026-07-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_ai_provider_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatebatch',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('geometric', 'Geometric')], default='geometric', max_length=20),
        ),
        migrations.AlterField(
            model_name='globaldesign',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('geometric', 'Geometric')], default='geometric', max_length=20),
        ),
    ]
