# Generated by Django 5.2.13 on 2026-07-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super administrador'), ('admin', 'Administrador'), ('professor', 'Profesor')], db_index=True, default='professor', max_length=20),
        ),
    ]
