# Generated by Django 5.2.14 on 2026-07-05 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_program_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='signature_inst_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_slot1', to='core.signature', verbose_name='Firma 1'),
        ),
        migrations.AddField(
            model_name='program',
            name='signature_inst_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_slot2', to='core.signature', verbose_name='Firma 2'),
        ),
        migrations.AddField(
            model_name='program',
            name='signature_inst_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_slot3', to='core.signature', verbose_name='Firma 3'),
        ),
        migrations.AddField(
            model_name='program',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('geometric', 'Geometric')], default='classic', max_length=20, verbose_name='Plantilla del certificado'),
        ),
    ]
