"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-_h4c*viqm#nm*7jr($qtcf=rt=9%bcg!h!d6j4esejzm6ckhnf')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

# Railway provides this automatically
RAILWAY_PUBLIC_DOMAIN = os.getenv('RAILWAY_PUBLIC_DOMAIN')
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

# Aceptar cualquier subdominio de Railway (web-production-*, certifai, custom, etc.)
ALLOWED_HOSTS.append('.railway.app')

CSRF_TRUSTED_ORIGINS = [
    f"https://{h}" for h in ALLOWED_HOSTS
    if h not in ('localhost', '127.0.0.1', '*') and not h.startswith('.')
]
CSRF_TRUSTED_ORIGINS.append('https://*.railway.app')

# Email — usamos la Gmail API de la cuenta institucional (Workspace).
# Requiere haber autorizado el scope gmail.send en /panel/google/connect/.
# Override con EMAIL_BACKEND en .env para tests (console / locmem / smtp).
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'core.services.email.backend.GmailAPIBackend')
DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL',
    f'CertifAI <{os.getenv("GOOGLE_OAUTH_EMAIL", "noreply@certifai.local")}>',
)
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Mantenemos las vars SMTP por si quieres caer al backend SMTP de Django temporalmente
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'django_filters',
    'corsheaders',
    # Local apps
    'core',
    'public',
    'admin_panel',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'admin_panel.context_processors.solicitudes_pendientes',
                'admin_panel.context_processors.nav_menu',
                'admin_panel.context_processors.design_tokens',
                'public.context_processors.participante',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=False,
    )
}
# En Railway la red privada tarda unos segundos en estar lista al arrancar.
# connect_timeout hace que la conexión falle rápido (y el startCommand reintente)
# en vez de colgarse indefinidamente.
if 'postgresql' in DATABASES['default'].get('ENGINE', ''):
    DATABASES['default'].setdefault('OPTIONS', {})['connect_timeout'] = 10


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
# En Railway el filesystem del contenedor es EFÍMERO: cada deploy borra lo subido.
# Para persistir imágenes/logos, montar un Volume de Railway y apuntar MEDIA_ROOT
# a su ruta (p.ej. MEDIA_ROOT=/data/media). En local queda BASE_DIR/media.
MEDIA_ROOT = os.getenv('MEDIA_ROOT', str(BASE_DIR / 'media'))

# === ALMACENAMIENTO DE ARCHIVOS ===
# Producción persistente y con CDN: Cloudinary. Se activa SOLO si existe la
# variable CLOUDINARY_URL (formato: cloudinary://<api_key>:<api_secret>@<cloud>).
# Sin ella, se usa disco local (dev). Asi las imágenes subidas dejan de
# perderse en cada deploy y se sirven desde el CDN (no consumen egress de la app).
_USE_CLOUDINARY = bool(os.getenv('CLOUDINARY_URL'))
if _USE_CLOUDINARY:
    INSTALLED_APPS += ['cloudinary_storage', 'cloudinary']

STORAGES = {
    'default': {
        'BACKEND': (
            'cloudinary_storage.storage.MediaCloudinaryStorage'
            if _USE_CLOUDINARY
            else 'django.core.files.storage.FileSystemStorage'
        ),
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

SITE_URL = os.getenv('SITE_URL', 'http://localhost:8001')

# ── Sentry (opcional, solo si SENTRY_DSN está configurado en producción) ──
SENTRY_DSN = os.getenv('SENTRY_DSN', '')
if SENTRY_DSN and not DEBUG:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
            send_default_pii=False,
            environment=os.getenv('SENTRY_ENV', 'production'),
        )
    except ImportError:
        pass  # sentry-sdk opcional; si no está instalado, ignorar

# Security settings for production
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Custom User Model
AUTH_USER_MODEL = 'core.User'

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'admin_panel.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Login Redirects
# Login Redirects
LOGIN_URL = 'panel:login'
LOGIN_REDIRECT_URL = 'panel:dashboard'
LOGOUT_REDIRECT_URL = 'panel:login'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Certificate Search Module Toggle
# Set to True to enable public certificate search/download
CERT_SEARCH_ENABLED = True

# ─── Django REST Framework ──────────────────────────────────────
from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'api.common.pagination.StandardPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}

# ─── Celery (tareas asíncronas) ─────────────────────────────────
# Si CELERY_BROKER_URL no está seteado y DEBUG=True, las tareas corren
# inmediatamente en el mismo proceso (eager mode) — útil en desarrollo
# sin redis instalado. En producción se requiere Redis o RabbitMQ.
CELERY_BROKER_URL     = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')
CELERY_TASK_ALWAYS_EAGER  = os.getenv('CELERY_TASK_ALWAYS_EAGER', 'False') == 'True' or DEBUG and not os.getenv('CELERY_BROKER_URL')
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = 'America/Guayaquil'
CELERY_TASK_TIME_LIMIT = 300       # 5 min hard kill
CELERY_TASK_SOFT_TIME_LIMIT = 240  # 4 min soft kill (catch SoftTimeLimitExceeded)
CELERY_BEAT_SCHEDULE = {
    # Cada 30 min revisa sesiones recién terminadas y dispara el pipeline
    # Drive → transcript → IA. Idempotente: skip si ya está LISTO.
    'process-past-events': {
        'task': 'core.tasks.transcript_tasks.process_past_events',
        'schedule': 60 * 30,   # 30 minutos
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CertifAI API',
    'DESCRIPTION': 'API REST para el sistema de certificados UNEMI / CertifAI.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}

CORS_ALLOWED_ORIGINS = [
    'http://localhost:8001',
    'http://127.0.0.1:8001',
    'http://localhost:8081',      # Expo dev
    'http://localhost:19006',     # Expo web
]
CORS_ALLOW_CREDENTIALS = True

# ── Google OAuth (Meet + Calendar + Drive) ─────────────────────────
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')
GOOGLE_REDIRECT_URI = os.getenv('GOOGLE_REDIRECT_URI', 'http://localhost:8000/admin/google/callback/')
GOOGLE_OAUTH_EMAIL = os.getenv('GOOGLE_OAUTH_EMAIL', '')
GOOGLE_OAUTH_SCOPES = [
    'https://www.googleapis.com/auth/calendar.events',
    'https://www.googleapis.com/auth/drive.readonly',
    'https://www.googleapis.com/auth/drive.file',
    'https://www.googleapis.com/auth/documents.readonly',
    'https://www.googleapis.com/auth/gmail.send',  # enviar correos como la cuenta institucional
    'https://www.googleapis.com/auth/userinfo.email',
    'openid',
]
